In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("CKD.csv")

In [3]:
df.head(5)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes

In [4]:
dup_count=df.duplicated().sum()
print('Printing Duplicate Count', df.duplicated().sum())

Printing Duplicate Count 0

In [5]:
print("Missing Value Check")
df.isnull().sum()

Missing Value Check

age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hrmo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [6]:
print("Shape of the Dateset :",df.shape)
print("Rows :", df.shape[0])
print("Columns :",df.shape[1])
print("\nDataset Columns and Types:")
print(df.dtypes)

Shape of the Dateset : (399, 25)
Rows : 399
Columns : 25

Dataset Columns and Types:
age               float64
bp                float64
sg                 object
al                float64
su                float64
rbc                object
pc                 object
pcc                object
ba                 object
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hrmo              float64
pcv               float64
wc                float64
rc                float64
htn                object
dm                 object
cad                object
appet              object
pe                 object
ane                object
classification     object
dtype: object

In [7]:
df['appet'] = df['appet'].map({'poor': 0, 'yes': 1})
df['classification'] = df['classification'].map({'no': 0, 'yes': 1})

In [8]:
df.nunique()

age                77
bp                 11
sg                  5
al                  6
su                  6
rbc                 2
pc                  2
pcc                 2
ba                  2
bgr               147
bu                119
sc                 85
sod                35
pot                41
hrmo              116
pcv                43
wc                 90
rc                 46
htn                 2
dm                  2
cad                 2
appet               2
pe                  2
ane                 2
classification      2
dtype: int64

In [9]:
for col in df.columns:
    unique_vals = df[col].unique()
    print("-"*60)
    print(f"Column: {col}")
    print(f"Total Unique Count: {len(unique_vals)}")
    print(f"Values: {unique_vals}")
    print("-" * 30)

------------------------------------------------------------
Column: age
Total Unique Count: 77
Values: [ 2.          3.          4.          5.          6.          7.
  8.         11.         12.         14.         15.         17.
 19.         20.         21.         22.         23.         24.
 25.         26.         27.         28.         29.         30.
 32.         33.         34.         35.         36.         37.
 38.         39.         40.         41.         42.         43.
 44.         45.         46.         47.         48.         49.
 50.         51.         52.         53.         54.         55.
 56.         57.         58.         59.         60.         61.
 62.         63.         64.         65.         66.         67.
 68.         69.         70.         71.         72.         73.
 74.         75.         76.         78.         79.         80.
 81.         82.         83.         90.         51.49230769]
------------------------------
------------------------------------------------------------
Column: bp
Total Unique Count: 11
Values: [ 76.45994832  50.          60.          80.          70.
  90.         100.         110.         140.         120.
 180.        ]
------------------------------
------------------------------------------------------------
Column: sg
Total Unique Count: 5
Values: ['c' 'a' 'd' 'b' 'e']
------------------------------
------------------------------------------------------------
Column: al
Total Unique Count: 6
Values: [3. 2. 1. 0. 4. 5.]
------------------------------
------------------------------------------------------------
Column: su
Total Unique Count: 6
Values: [0. 4. 3. 2. 1. 5.]
------------------------------
------------------------------------------------------------
Column: rbc
Total Unique Count: 2
Values: ['normal' 'abnormal']
------------------------------
------------------------------------------------------------
Column: pc
Total Unique Count: 2
Values: ['abnormal' 'normal']
------------------------------
------------------------------------------------------------
Column: pcc
Total Unique Count: 2
Values: ['notpresent' 'present']
------------------------------
------------------------------------------------------------
Column: ba
Total Unique Count: 2
Values: ['notpresent' 'present']
------------------------------
------------------------------------------------------------
Column: bgr
Total Unique Count: 147
Values: [148.11267606  99.          94.          78.          80.
 100.         192.          86.          93.          92.
  22.         114.         107.         123.          97.
  70.         111.          95.         410.         140.
 125.         121.         119.          88.         250.
  76.         131.          79.         127.          83.
 101.          96.          89.         138.         120.
  82.         102.         128.         130.         153.
 139.         117.         104.          91.          87.
 105.         103.          85.         109.         124.
 253.         210.         122.         112.          98.
 132.          75.          81.         108.         106.
 425.         360.         268.         113.         150.
 163.         213.         160.         204.         137.
 133.         214.         129.         490.         219.
 230.         224.         116.         207.         208.
 162.         233.         352.         146.         143.
 297.         273.         118.         165.         415.
 298.         242.         176.         251.         303.
 252.         255.         241.         424.          74.
 263.         144.         172.         288.         261.
 269.         134.         173.         159.         423.
 246.         309.         169.         380.         280.
 239.         463.         270.         115.         294.
  90.         307.         215.         203.         447.
 248.         141.         182.         341.         157.
 171.         238.         264.         256.         158.
 184.         323.         308.          84.         201.
 295.         234.         156.         110.         226.
 148.         220.        ]
------------------------------
------------------------------------------------------------
Column: bu
Total Unique Count: 119
Values: [ 57.48210526  22.          23.          16.          25.
  67.          18.          27.          46.          66.
  17.          51.          26.          15.          32.
   1.5         50.          44.          40.          36.
  34.          24.          31.          19.          42.
  20.          29.          49.         106.          38.
 223.          37.          41.         219.          28.
  33.         202.          30.          39.          35.
  47.          77.         162.         150.          10.
  68.         165.          48.         153.          45.
  86.          52.          93.          80.         111.
  92.          87.          56.         163.         139.
  79.         215.         158.          55.         118.
 208.         176.          60.         166.         107.
 114.          89.          50.1         21.         146.
 137.          88.          53.         235.          73.
 132.         309.         322.          96.         186.
 191.         180.          72.          58.          95.
 148.          75.         113.          61.          94.
  54.          64.          71.          98.         133.
  82.          76.         391.          90.          57.
 103.          85.         125.          98.6         65.
 145.         241.         142.         164.         155.
 217.          74.          70.         115.        ]
------------------------------
------------------------------------------------------------
Column: sc
Total Unique Count: 85
Values: [ 3.07735602  0.7         0.6         1.          0.8         0.9
  2.5         1.8         2.1         7.3         1.7         1.2
  1.1         0.5         3.9         6.5        18.1         0.4
 12.2         2.2         1.6        10.8         1.3         1.9
  9.6        11.9         2.8        18.          1.4         2.7
  2.4         4.          2.3         6.1         3.3         2.
  5.2        16.9         3.8         7.7         8.5         5.3
 15.2        11.8         9.2        13.8         5.6         7.2
  3.25        6.3         5.9         7.5        14.2         6.7
 16.4        13.3        13.          9.3         1.5         6.4
 15.          3.2        12.8        12.         76.          3.
  2.9         3.4         4.3        11.5         4.4        13.5
 32.          6.         24.          4.6         4.1        48.1
  3.6         7.1        13.4         9.7        10.2         2.6
  6.8       ]
------------------------------
------------------------------------------------------------
Column: sod
Total Unique Count: 35
Values: [137.52875399 138.         135.         142.         137.
 136.         141.         145.         125.         150.
 140.         127.         139.         147.         144.
 146.         113.         133.         130.         134.
 132.         129.         143.         128.         131.
 111.         120.         122.         114.         124.
 126.           4.5        163.         104.         115.        ]
------------------------------
------------------------------------------------------------
Column: pot
Total Unique Count: 41
Values: [ 4.62724359  4.4         3.2         4.9         3.8         3.6
  4.2         4.          3.9         2.8         4.7         3.5
  4.3         4.6         5.          3.3         4.8         6.5
  4.5         4.1         3.4         3.7         5.6         5.1
  6.3         5.2         2.5         5.5         5.7        47.
  5.3         7.6         2.9         3.          5.4         6.6
 39.          5.8         6.4         5.9         2.7       ]
------------------------------
------------------------------------------------------------
Column: hrmo
Total Unique Count: 116
Values: [12.51815562 10.7        12.          8.1        11.8         9.9
 11.3        12.3        12.2        15.         12.1        15.8
 14.3        11.         16.7        13.9        13.1        14.2
 11.5        14.4        14.         14.6         8.3        13.5
 17.         17.7        12.4        16.3        15.4        15.2
 13.3        15.6        17.6        14.8        17.5        13.7
 14.1        13.8        13.4        14.9         5.5        16.9
 15.5         6.         12.7        11.9        13.6        15.3
 17.1         7.9         9.5        16.1        14.5        14.7
 16.2        10.9         7.6        11.1        16.8         9.8
 16.6        16.5        15.9        17.8        13.         10.
  7.5         9.3         9.         15.7        13.2        16.4
 12.6         9.7        10.8        11.2        10.3         6.3
  8.6         9.4         6.2         8.2        11.6        17.2
 11.7        11.4        17.3         9.1         8.4         3.1
  8.          6.8        10.4         6.6         7.1         7.3
  9.6        10.1         7.7        17.4        10.6        12.8
 10.5         8.8        12.5        16.          6.1         5.6
 12.9         5.8        15.1         9.2        10.2         8.7
  4.8         8.5       ]
------------------------------
------------------------------------------------------------
Column: pcv
Total Unique Count: 43
Values: [38.86890244 34.         36.         30.         38.         41.
 45.         49.         40.         33.         50.         52.
 51.         44.         23.         42.         46.         48.
 43.         54.         15.         39.         47.         24.
 28.         32.         31.         29.         37.         26.
 27.         19.         18.         17.         22.         35.
  9.         53.         20.         25.         21.         16.
 14.        ]
------------------------------
------------------------------------------------------------
Column: wc
Total Unique Count: 90
Values: [ 8408.19112628 12300.         12400.         16700.
  6000.          6700.          8600.         10300.
  6600.          9500.          7700.          6200.
  7000.         11200.          7200.          6900.
  4500.          5500.          7900.          9800.
  4300.          6300.          5800.          5600.
 10700.          9200.          6500.          9900.
  5400.          9400.          9000.         10200.
  2600.          6800.          7800.          2200.
 10500.          7400.          5000.          8800.
  4100.          9100.          7300.          3800.
 10400.          8300.          8400.          7100.
 14900.          9600.          7500.         19100.
  5700.         14600.          8100.         11000.
  5200.          6400.         16300.         13200.
  4700.         12100.         13600.          8200.
 11800.         12500.          4200.         10900.
 26400.         15700.         11400.         21600.
 15200.         12000.         10800.          5300.
  8500.         12800.          8000.         11900.
  5900.         12200.          4900.         11500.
  9300.          9700.         18900.         11300.
 12700.          5100.        ]
------------------------------
------------------------------------------------------------
Column: rc
Total Unique Count: 46
Values: [4.70559701 4.8        5.4        3.8        5.2        5.9
 5.5        3.9        6.4        5.         4.6        5.6
 4.5        6.3        5.3        4.9        6.         6.5
 4.7        5.8        2.8        5.1        6.1        3.1
 6.2        5.7        3.4        4.4        3.7        4.2
 4.1        3.2        4.3        4.         2.6        2.5
 3.5        2.3        2.7        2.9        3.6        3.
 2.1        3.3        8.         2.4       ]
------------------------------
------------------------------------------------------------
Column: htn
Total Unique Count: 2
Values: ['no' 'yes']
------------------------------
------------------------------------------------------------
Column: dm
Total Unique Count: 2
Values: ['no' 'yes']
------------------------------
------------------------------------------------------------
Column: cad
Total Unique Count: 2
Values: ['no' 'yes']
------------------------------
------------------------------------------------------------
Column: appet
Total Unique Count: 2
Values: [1 0]
------------------------------
------------------------------------------------------------
Column: pe
Total Unique Count: 2
Values: ['yes' 'poor']
------------------------------
------------------------------------------------------------
Column: ane
Total Unique Count: 2
Values: ['no' 'yes']
------------------------------
------------------------------------------------------------
Column: classification
Total Unique Count: 2
Values: [1 0]
------------------------------

In [10]:
print(df.dtypes)

age               float64
bp                float64
sg                 object
al                float64
su                float64
rbc                object
pc                 object
pcc                object
ba                 object
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hrmo              float64
pcv               float64
wc                float64
rc                float64
htn                object
dm                 object
cad                object
appet               int64
pe                 object
ane                object
classification      int64
dtype: object

In [11]:
mapping = {
    'normal': 1, 'abnormal': 0,
    'present': 1, 'notpresent': 0,
    'yes': 1, 'no': 0,
    'poor': 0 
}

binary_cols = ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'pe', 'ane']

for col in binary_cols:
    df[col] = df[col].map(mapping)

df_final = pd.get_dummies(df, drop_first=True)

In [12]:
df_final.head(5)

,age,bp,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,sg_b,sg_c,sg_d,sg_e
0,2.0,76.459948,3.0,0.0,1,0,0,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597,0,0,0,1,1,0,1,False,True,False,False
1,3.0,76.459948,2.0,0.0,1,1,0,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,34.000000,12300.000000,4.705597,0,0,0,1,0,0,1,False,True,False,False
2,4.0,76.459948,1.0,0.0,1,1,0,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,34.000000,8408.191126,4.705597,0,0,0,1,0,0,1,False,False,False,False
3,5.0,76.459948,1.0,0.0,1,1,0,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,38.868902,8408.191126,4.705597,0,0,0,1,0,1,1,False,False,True,False
4,5.0,50.000000,0.0,0.0,1,1,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,36.000000,12400.000000,4.705597,0,0,0,1,0,0,1,False,True,False,False

In [13]:
df_final = df_final.astype(int)

In [14]:
for col in df_final.columns:
    unique_vals = df_final[col].unique()
    print("-"*60)
    print(f"Column: {col}")
    print(f"Total Unique Count: {len(unique_vals)}")
    print(f"Values: {unique_vals}")
    print("-" * 30)

------------------------------------------------------------
Column: age
Total Unique Count: 76
Values: [ 2  3  4  5  6  7  8 11 12 14 15 17 19 20 21 22 23 24 25 26 27 28 29 30
 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55
 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 78 79 80
 81 82 83 90]
------------------------------
------------------------------------------------------------
Column: bp
Total Unique Count: 11
Values: [ 76  50  60  80  70  90 100 110 140 120 180]
------------------------------
------------------------------------------------------------
Column: al
Total Unique Count: 6
Values: [3 2 1 0 4 5]
------------------------------
------------------------------------------------------------
Column: su
Total Unique Count: 6
Values: [0 4 3 2 1 5]
------------------------------
------------------------------------------------------------
Column: rbc
Total Unique Count: 2
Values: [1 0]
------------------------------
------------------------------------------------------------
Column: pc
Total Unique Count: 2
Values: [0 1]
------------------------------
------------------------------------------------------------
Column: pcc
Total Unique Count: 2
Values: [0 1]
------------------------------
------------------------------------------------------------
Column: ba
Total Unique Count: 2
Values: [0 1]
------------------------------
------------------------------------------------------------
Column: bgr
Total Unique Count: 146
Values: [148  99  94  78  80 100 192  86  93  92  22 114 107 123  97  70 111  95
 410 140 125 121 119  88 250  76 131  79 127  83 101  96  89 138 120  82
 102 128 130 153 139 117 104  91  87 105 103  85 109 124 253 210 122 112
  98 132  75  81 108 106 425 360 268 113 150 163 213 160 204 137 133 214
 129 490 219 230 224 116 207 208 162 233 352 146 143 297 273 118 165 415
 298 242 176 251 303 252 255 241 424  74 263 144 172 288 261 269 134 173
 159 423 246 309 169 380 280 239 463 270 115 294  90 307 215 203 447 248
 141 182 341 157 171 238 264 256 158 184 323 308  84 201 295 234 156 110
 226 220]
------------------------------
------------------------------------------------------------
Column: bu
Total Unique Count: 116
Values: [ 57  22  23  16  25  67  18  27  46  66  17  51  26  15  32   1  50  44
  40  36  34  24  31  19  42  20  29  49 106  38 223  37  41 219  28  33
 202  30  39  35  47  77 162 150  10  68 165  48 153  45  86  52  93  80
 111  92  87  56 163 139  79 215 158  55 118 208 176  60 166 107 114  89
  21 146 137  88  53 235  73 132 309 322  96 186 191 180  72  58  95 148
  75 113  61  94  54  64  71  98 133  82  76 391  90 103  85 125  65 145
 241 142 164 155 217  74  70 115]
------------------------------
------------------------------------------------------------
Column: sc
Total Unique Count: 22
Values: [ 3  0  1  2  7  6 18 12 10  9 11  4  5 16  8 15 13 14 76 32 24 48]
------------------------------
------------------------------------------------------------
Column: sod
Total Unique Count: 34
Values: [137 138 135 142 136 141 145 125 150 140 127 139 147 144 146 113 133 130
 134 132 129 143 128 131 111 120 122 114 124 126   4 163 104 115]
------------------------------
------------------------------------------------------------
Column: pot
Total Unique Count: 8
Values: [ 4  3  2  5  6 47  7 39]
------------------------------
------------------------------------------------------------
Column: hrmo
Total Unique Count: 15
Values: [12 10  8 11  9 15 14 16 13 17  5  6  7  3  4]
------------------------------
------------------------------------------------------------
Column: pcv
Total Unique Count: 42
Values: [38 34 36 30 41 45 49 40 33 50 52 51 44 23 42 46 48 43 54 15 39 47 24 28
 32 31 29 37 26 27 19 18 17 22 35  9 53 20 25 21 16 14]
------------------------------
------------------------------------------------------------
Column: wc
Total Unique Count: 90
Values: [ 8408 12300 12400 16700  6000  6700  8600 10300  6600  9500  7700  6200
  7000 11200  7200  6900  4500  5500  7900  9800  4300  6300  5800  5600
 10700  9200  6500  9900  5400  9400  9000 10200  2600  6800  7800  2200
 10500  7400  5000  8800  4100  9100  7300  3800 10400  8300  8400  7100
 14900  9600  7500 19100  5700 14600  8100 11000  5200  6400 16300 13200
  4700 12100 13600  8200 11800 12500  4200 10900 26400 15700 11400 21600
 15200 12000 10800  5300  8500 12800  8000 11900  5900 12200  4900 11500
  9300  9700 18900 11300 12700  5100]
------------------------------
------------------------------------------------------------
Column: rc
Total Unique Count: 6
Values: [4 5 3 6 2 8]
------------------------------
------------------------------------------------------------
Column: htn
Total Unique Count: 2
Values: [0 1]
------------------------------
------------------------------------------------------------
Column: dm
Total Unique Count: 2
Values: [0 1]
------------------------------
------------------------------------------------------------
Column: cad
Total Unique Count: 2
Values: [0 1]
------------------------------
------------------------------------------------------------
Column: appet
Total Unique Count: 2
Values: [1 0]
------------------------------
------------------------------------------------------------
Column: pe
Total Unique Count: 2
Values: [1 0]
------------------------------
------------------------------------------------------------
Column: ane
Total Unique Count: 2
Values: [0 1]
------------------------------
------------------------------------------------------------
Column: classification
Total Unique Count: 2
Values: [1 0]
------------------------------
------------------------------------------------------------
Column: sg_b
Total Unique Count: 2
Values: [0 1]
------------------------------
------------------------------------------------------------
Column: sg_c
Total Unique Count: 2
Values: [1 0]
------------------------------
------------------------------------------------------------
Column: sg_d
Total Unique Count: 2
Values: [0 1]
------------------------------
------------------------------------------------------------
Column: sg_e
Total Unique Count: 2
Values: [0 1]
------------------------------

In [15]:
X = df_final.drop(columns=['classification'])
y = df_final['classification']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
classifier_log = LogisticRegression(random_state=0)
classifier_log.fit(X_train, y_train)

y_pred_log = classifier_log.predict(X_test)
print("Logistic Regression Confusion Matrix:\n", confusion_matrix(y_test, y_pred_log))
print("\nReport:\n", classification_report(y_test, y_pred_log))

Logistic Regression Confusion Matrix:
 [[51  0]
 [ 1 81]]

Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [18]:
classifier_svm = SVC(kernel='sigmoid', probability=True, random_state=0)
classifier_svm.fit(X_train, y_train)

y_pred_svm = classifier_svm.predict(X_test)
print("SVM Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))
print("\nReport:\n", classification_report(y_test, y_pred_svm))

SVM Confusion Matrix:
 [[51  0]
 [ 1 81]]

Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [19]:
classifier_rf = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)
classifier_rf.fit(X_train, y_train)

y_pred_rf = classifier_rf.predict(X_test)
print("Random Forest Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("\nReport:\n", classification_report(y_test, y_pred_rf))

Random Forest Confusion Matrix:
 [[50  1]
 [ 1 81]]

Report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        51
           1       0.99      0.99      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

In [20]:
classifier_knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier_knn.fit(X_train, y_train)

y_pred_knn = classifier_knn.predict(X_test)
print("KNN Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))
print("\nReport:\n", classification_report(y_test, y_pred_knn))

KNN Confusion Matrix:
 [[51  0]
 [ 6 76]]

Report:
               precision    recall  f1-score   support

           0       0.89      1.00      0.94        51
           1       1.00      0.93      0.96        82

    accuracy                           0.95       133
   macro avg       0.95      0.96      0.95       133
weighted avg       0.96      0.95      0.96       133

In [21]:
classifier_nb = GaussianNB()
classifier_nb.fit(X_train, y_train)

y_pred_nb = classifier_nb.predict(X_test)
print("Naive Bayes Confusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))
print("\nReport:\n", classification_report(y_test, y_pred_nb))

Naive Bayes Confusion Matrix:
 [[51  0]
 [ 3 79]]

Report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

In [22]:
scores = cross_val_score(classifier_rf, X, y, cv=5)

print("Cross-Validation Accuracy Scores:", scores)
print("Average Accuracy: {:.2f}%".format(scores.mean() * 100))

Cross-Validation Accuracy Scores: [0.9375 1.     0.975  0.9875 1.    ]
Average Accuracy: 98.00%